### PR TITLE
Fix some warnings

### PR DESCRIPTION
**Pull request by nils-eilers**

### CODE REVIEW

**Comment by nealcrook** [comment]
Thanks for a great tidy-up. Are you looking to do some kind of CBM/6809 hybrid?

**Comment by nils-eilers** [comment]
Thank you!

Such a CBM/6809 hybrid existed and was sold as "SuperPET" or "MMF 9000". Dave Roberts was/is(?) working on a SuperPET2: http://www.vcfed.org/forum/showthread.php?48829-Commodore-8032-add-on-board-SuperPET&p=403172#post403172

My plans are much simpler: I'm just still dreaming of my own 6309-based SBC.

**Comment by nealcrook** [comment]
Do you have the chips? I have 2 never-used HD63B09EP devices and I'd consider swapping one for a blank PCB. I've had lots of thoughts about what a small board might look like for this chip, but it always ends up with so much "modern" chippery to keep the parts-count down, that it seems too much of a cheat (for example, I thought of completely slaving the 6309 to an Atmel part in the same way as somebody on 6502.org did with a 6502/PIC). Also, there's pretty much zero software.. though you could do a gcc port (!!) and run FUZIX. Have you looked at the multicomp design ("only" 6809 though).

I swapped emails with Dave Roberts at the start of the year; he was looking for help doing a NITROS9 port to his SuperPET2 and I offered assistance. Haven't heard from him since February though.

**Comment by nils-eilers** [comment]
Don't count your chicken before they're hatched. I stopped working on the actual hardware design in favour of preparing some system software first. Some operating systems may have special hardware requirements that I'm not yet aware of so I'd like to clarify that first.

Thank you for pointing to the multicomp, FPGA board ordered today. I've got some questions whose scope is beyond these commits so I'd like to move this discussion off github. I haven't been able to find your e-mail address so may I please ask you to drop me a line to nils.eilers@gmx.de?

**Pull request merged**
